# Name of your asset.
name = "bevy_ineffable"

# Description of your asset. It should be less than 100 characters and not contain formatting.
description = "A simple-to-use input manager for bevy that empowers players and makes accessibility easy."

# Where can your asset be found. It can be a link to crates.io, github, gitlab or similar.
link = "https://github.com/Jazarro/bevy_ineffable"

# Optional image to showcase your asset.
# Should be a png/jpg/gif/webp located next to your toml file, less than 2 MB in size.
# image = "bevy_ineffable.png"
